PROGRAM SPMD_EXAMPLE

  USE OMP_LIB

  IMPLICIT NONE

  INTEGER, PARAMETER                 :: N = 100000000
  REAL(8), DIMENSION(:), ALLOCATABLE :: A
  INTEGER                            :: NUM_THREADS, TID, I

  ALLOCATE(A(N), SOURCE = 1.0_8)

  NUM_THREADS = 4
  CALL OMP_SET_NUM_THREADS(NUM_THREADS)

  !$OMP PARALLEL PRIVATE(I, TID)
    TID = OMP_GET_THREAD_NUM()
    DO I = TID + 1, N, NUM_THREADS
      A(I) = 2.0_8 * A(I)
    END DO
  !$OMP END PARALLEL

  DEALLOCATE(A)

END PROGRAM SPMD_EXAMPLE
